<a href="https://colab.research.google.com/github/hajing09-dev/numpy_and_matrix/blob/main/numpy_and_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

온라인 코드 실행기에 오신것을 환영합니다!

⬇ 아래의 실행 버튼을 눌러 코드를 실행할수 있습니다.

In [19]:
# 기본적인 numpy 코드
import numpy as np

# 행렬 만들기(여기서 수를 변경하면 결과가 바뀌지만 덧셈, 곱셈할때 필요한 규칙은 지켜서 넣어주세요)
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 0], [0, 1]])  # 단위 행렬

# 결과 계산해서 변수에 저장
add_result = A + B          # 행렬 덧셈
sub_result = A - B          # 행렬 뺄셈
dot_result = A @ B          # 행렬 곱셈

# 출력
print("행렬 A:")
print(A)

print("\n행렬 B (단위행렬):")
print(B)

print("\nA + B (행렬의 덧셈):")
print(add_result)

print("\nA - B (행렬의 뺄셈):")
print(sub_result)

print("\nA @ B (행렬의 곱셈):")
print(dot_result)


# A의 행과 열의 개수 확인
print("\nA의 행 개수:", A.shape[0])
print("A의 열 개수:", A.shape[1])


행렬 A:
[[1 2]
 [3 4]]

행렬 B (단위행렬):
[[1 0]
 [0 1]]

A + B (행렬의 덧셈):
[[2 2]
 [3 5]]

A - B (행렬의 뺄셈):
[[0 2]
 [3 3]]

A @ B (행렬의 곱셈):
[[1 2]
 [3 4]]

A의 행 개수: 2
A의 열 개수: 2


In [12]:
#행렬을 입력받아 행과 열의 수를 알려주는 코드입니다.

import ipywidgets as widgets
from IPython.display import display, clear_output
import numpy as np

matrix_input = widgets.Textarea(
    value='',
    placeholder='예: 1,2,3\n4,5,6\n7,8,9',
    description='행렬 입력:',
    layout=widgets.Layout(width='50%', height='100px')
)

output = widgets.Output()

def parse_matrix_with_numpy(text):
    try:
        # 줄바꿈으로 행 분리 후 쉼표로 열 분리해서 리스트로 만듦
        rows = text.strip().split('\n')
        data = [list(map(float, row.split(','))) for row in rows]
        arr = np.array(data)

        # numpy array가 2차원이 아니면 오류 처리
        if arr.ndim != 2:
            return None, "2차원 행렬 형식으로 입력해주세요."
        return arr, None
    except Exception:
        return None, "입력 형식 오류: 숫자를 쉼표로 구분하고 줄바꿈으로 행을 나누세요."

def on_button_clicked(b):
    with output:
        clear_output()
        matrix_text = matrix_input.value
        arr, error = parse_matrix_with_numpy(matrix_text)
        if error:
            print("오류:", error)
        else:
            print(f"입력한 행렬의 행 개수: {arr.shape[0]}")
            print(f"입력한 행렬의 열 개수: {arr.shape[1]}")

button = widgets.Button(description="행렬 정보 확인")
button.on_click(on_button_clicked)

display(matrix_input, button, output)


Textarea(value='', description='행렬 입력:', layout=Layout(height='100px', width='50%'), placeholder='예: 1,2,3\n4,…

Button(description='행렬 정보 확인', style=ButtonStyle())

Output()

In [10]:
#행렬 계산기

import numpy as np
import ipywidgets as widgets
from IPython.display import display, clear_output

out = widgets.Output()

def input_screen(prev_A=None, prev_B=None,
                 prev_rows_a=2, prev_cols_a=2,
                 prev_rows_b=2, prev_cols_b=2):
    clear_output()
    out.clear_output()  # 에러 메시지 초기화

    rows_a_input = widgets.BoundedIntText(value=prev_rows_a, min=1, max=10, description='A 행:', layout=widgets.Layout(width='150px'))
    cols_a_input = widgets.BoundedIntText(value=prev_cols_a, min=1, max=10, description='A 열:', layout=widgets.Layout(width='150px'))
    rows_b_input = widgets.BoundedIntText(value=prev_rows_b, min=1, max=10, description='B 행:', layout=widgets.Layout(width='150px'))
    cols_b_input = widgets.BoundedIntText(value=prev_cols_b, min=1, max=10, description='B 열:', layout=widgets.Layout(width='150px'))

    btn_next = widgets.Button(description='다음')

    def on_next_clicked(b):
        r_a, c_a = rows_a_input.value, cols_a_input.value
        r_b, c_b = rows_b_input.value, cols_b_input.value

        if c_a != r_b:
            with out:
                clear_output()
                print("행렬 곱을 위해 A의 열과 B의 행 크기가 같아야 합니다.")
            return

        input_matrix_screen(r_a, c_a, r_b, c_b, prev_A, prev_B)

    btn_next.on_click(on_next_clicked)

    box = widgets.VBox([rows_a_input, cols_a_input, rows_b_input, cols_b_input, btn_next, out])
    display(box)

def input_matrix_screen(r_a, c_a, r_b, c_b, prev_A=None, prev_B=None):
    clear_output()
    out.clear_output()

    A_inputs = []
    B_inputs = []

    def create_matrix_widgets(rows, cols, prev_values):
        inputs = []
        for i in range(rows):
            row_widgets = []
            for j in range(cols):
                val = ''
                if prev_values is not None:
                    try:
                        val = str(prev_values[i][j])
                    except:
                        pass
                w = widgets.Text(value=val, layout=widgets.Layout(width='40px'))
                row_widgets.append(w)
            inputs.append(row_widgets)
        return inputs

    A_inputs = create_matrix_widgets(r_a, c_a, prev_A)
    B_inputs = create_matrix_widgets(r_b, c_b, prev_B)

    def matrix_widget_to_array(matrix_widgets):
        rows = len(matrix_widgets)
        cols = len(matrix_widgets[0]) if rows > 0 else 0
        arr = np.zeros((rows, cols), dtype=float)
        for i in range(rows):
            for j in range(cols):
                try:
                    arr[i, j] = float(matrix_widgets[i][j].value)
                except:
                    arr[i, j] = 0
        return arr

    btn_add = widgets.Button(description='덧셈 (A + B)')
    btn_sub = widgets.Button(description='뺄셈 (A - B)')
    btn_mul = widgets.Button(description='곱셈 (A x B)')
    btn_prev = widgets.Button(description='이전')

    output_calc = widgets.Output()

    def on_add_clicked(b):
        output_calc.clear_output()
        A = matrix_widget_to_array(A_inputs)
        B = matrix_widget_to_array(B_inputs)
        with output_calc:
            clear_output()
            if A.shape == B.shape:
                print("A + B =\n", A + B)
            else:
                print("덧셈 불가능 (행렬 크기 불일치)")

    def on_sub_clicked(b):
        output_calc.clear_output()
        A = matrix_widget_to_array(A_inputs)
        B = matrix_widget_to_array(B_inputs)
        with output_calc:
            clear_output()
            if A.shape == B.shape:
                print("A - B =\n", A - B)
            else:
                print("뺄셈 불가능 (행렬 크기 불일치)")

    def on_mul_clicked(b):
        output_calc.clear_output()
        A = matrix_widget_to_array(A_inputs)
        B = matrix_widget_to_array(B_inputs)
        with output_calc:
            clear_output()
            if A.shape[1] == B.shape[0]:
                print("A x B =\n", A @ B)
            else:
                print("곱셈 불가능 (A의 열 수와 B의 행 수 불일치)")

    def on_prev_clicked(b):
        prev_A = matrix_widget_to_array(A_inputs).tolist()
        prev_B = matrix_widget_to_array(B_inputs).tolist()
        input_screen(
            prev_A=prev_A, prev_B=prev_B,
            prev_rows_a=r_a, prev_cols_a=c_a,
            prev_rows_b=r_b, prev_cols_b=c_b
        )

    btn_add.on_click(on_add_clicked)
    btn_sub.on_click(on_sub_clicked)
    btn_mul.on_click(on_mul_clicked)
    btn_prev.on_click(on_prev_clicked)

    A_grid = widgets.GridBox(
        [item for row in A_inputs for item in row],
        layout=widgets.Layout(
            grid_template_columns=" ".join(["40px"]*c_a),
            grid_gap="5px"
        )
    )
    B_grid = widgets.GridBox(
        [item for row in B_inputs for item in row],
        layout=widgets.Layout(
            grid_template_columns=" ".join(["40px"]*c_b),
            grid_gap="5px"
        )
    )

    display(widgets.HTML(value="<b>A 행렬 입력</b>"))
    display(A_grid)
    display(widgets.HTML(value="<b>B 행렬 입력</b>"))
    display(B_grid)
    display(widgets.HBox([btn_add, btn_sub, btn_mul, btn_prev]))
    display(output_calc)

input_screen()


HTML(value='<b>A 행렬 입력</b>')

GridBox(children=(Text(value='0.0', layout=Layout(width='40px')), Text(value='5.0', layout=Layout(width='40px'…

HTML(value='<b>B 행렬 입력</b>')

GridBox(children=(Text(value='5.0', layout=Layout(width='40px')), Text(value='8.0', layout=Layout(width='40px'…

Output()